collections:
  - homework
  - team
  - servers

defaults:
  -
    scope:
      path: "_homework"
    values:
      layout: "homework"
  -
    scope:
      path: "_team"
    values:
      layout: "team_member"
  -
    scope:
      path: "_servers"
    values:
      layout: "server_items"

title: Limelight Gaming

plugins:
  - jekyll-seo-tag

tagline: "Take the Limelight."
description: "Information about Limelight Gaming and its projects."
logo: "/assets/img/logo.png"

social:
  links:
    - https://github.com/limelight-development/
    - https://steamcommunity.com/groups/LimeLightG
    - https://limelightgaming.net/

lang: en_GB
locale: en_GB

twitter:
  card: summary
  username: l2_gaming
