name: Deployment
on: push

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: rlespinasse/github-slug-action@1.1.0
    - name: Deploy Live
      uses: burnett01/rsync-deployments@4.0
      with:
        switches: -avzrOv --no-perms --no-o --no-g --delete --filter="merge .github/filter"
        remote_path: ~/limelight-info/${{ env.GITHUB_REF_SLUG }}
        remote_host: ${{secrets.DEPLOY_HOST}}	
        remote_user: ${{secrets.DEPLOY_USER}}
        remote_key: ${{secrets.DEPLOY_KEY}}
