name: Deployment
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Deploy Live
      uses: burnett01/rsync-deployments@4.0
      with:
        switches: -avzrO --no-perms --no-o --no-g --delete --filter="merge .github/filter"
        remote_path: /home/deployment/limelight-info
        remote_host: ${{secrets.DEPLOY_HOST}}	
        remote_user: ${{secrets.DEPLOY_USER}}
        remote_key: ${{secrets.DEPLOY_KEY}}
