on:
  delete

name: Deleted Branch Staging Cleanup

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Cleanup
    steps:
      - name: Dump Event context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$GITHUB_CONTEXT"
