on:
  push:
    branches-ignore:
      - gh-pages

name: Page Build & Deployment

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: (cat Gemfile.lock > /dev/null && (sudo gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)") || sudo gem install bundler) && bundler config set deployment 'true' && bundler install
      - name: Get Deployment Root
        id: branch_root
        run: .github/scripts/branch-root.sh
      - name: Build Site
        run: bundle exec jekyll build --baseurl "${{ steps.branch_root.outputs.deploy_baseurl }}"
      - name: Deploy Site
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: _site
          target-folder: ${{ steps.branch_root.outputs.deploy_root }}
          clean-exclude: ${{ steps.branch_root.outputs.deploy_exclude }}
